name: homelab
networks:
  traefik:
    name: traefik
    enable_ipv6: true
  backend:
    name: backend
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.13.0/24
        - subnet: fd16:dd1a:c8e5:3::/64
  frontend:
    name: frontend
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.12.0/24
        - subnet: fd16:dd1a:c8e5:2::/64
  socket_proxy:
    name: socket_proxy
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 192.168.11.0/24
        - subnet: fd16:dd1a:c8e5:1::/64

secrets:
  cf_dns_api_tokens:
    file: $DOCKERDIR/.secrets/cf_dns_api_tokens
  pgsql_root_password:
    file: $DOCKERDIR/.secrets/pgsql_root_password
  basic_auth_credentials:
    file: $DOCKERDIR/.secrets/basic_auth_credentials
  cloudflare:
    file: $DOCKERDIR/.secrets/cloudflare

include:
  # CORE
  - compose/$HOSTNAME/adguard.yaml
  # - compose/$HOSTNAME/audiobookshelf.yaml
  - compose/$HOSTNAME/certbot.yaml
  - compose/$HOSTNAME/crowdsec.yaml
  - compose/$HOSTNAME/deunhealth.yaml
  - compose/$HOSTNAME/dozzle.yaml
  - compose/$HOSTNAME/homepage.yaml
  - compose/$HOSTNAME/portainer.yaml
  - compose/$HOSTNAME/protonmail-bridge.yaml
  - compose/$HOSTNAME/proxy.yaml
  - compose/$HOSTNAME/socket-proxy.yaml
  - compose/$HOSTNAME/traefik-bouncer.yaml
  - compose/$HOSTNAME/unifi.yaml
  # DOWNLOADERS
  - compose/$HOSTNAME/qbittorrent.yaml
  - compose/$HOSTNAME/sabnzbd.yaml
  # PVRS
  - compose/$HOSTNAME/jellyseer.yaml
  - compose/$HOSTNAME/prowlarr.yaml
  - compose/$HOSTNAME/radarr.yaml
  - compose/$HOSTNAME/readarr.yaml
  - compose/$HOSTNAME/sonarr.yaml
  - compose/$HOSTNAME/bazarr.yaml
  - compose/$HOSTNAME/qbitrr.yaml
  - compose/$HOSTNAME/recyclarr.yaml
  # MONITORING
  - compose/$HOSTNAME/prometheus.yaml
  - compose/$HOSTNAME/grafana.yaml
  - compose/$HOSTNAME/exportarr.yaml
  - compose/$HOSTNAME/nodeexporter.yaml
  - compose/$HOSTNAME/cadvisor.yaml
  # MAINTENANCE
  - compose/$HOSTNAME/docker-gc.yaml
  # NETWORK
  - compose/$HOSTNAME/gluetun.yaml
  # WEB
  - compose/$HOSTNAME/webapp.yaml
  - compose/$HOSTNAME/mealie.yaml
