name: homelab
networks:
  traefik:
    name: traefik
    enable_ipv6: true
    ipam:
      config:
        - subnet: fe81::/112
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.13.0/24
  frontend:
    name: frontend
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24

secrets:
  cf_dns_api_tokens:
    file: $DOCKERDIR/.secrets/cf_dns_api_tokens
  pgsql_root_password:
    file: $DOCKERDIR/.secrets/pgsql_root_password
  basic_auth_credentials:
    file: $DOCKERDIR/.secrets/basic_auth_credentials

include:
  # CORE
  - compose/$HOSTNAME/socket-proxy.yaml
  - compose/$HOSTNAME/portainer.yaml
  - compose/$HOSTNAME/dozzle.yaml
  - compose/$HOSTNAME/homepage.yaml
  - compose/$HOSTNAME/adguard.yaml
  - compose/$HOSTNAME/proxy.yaml
  # MEDIA
  # DOWNLOADERS
  - compose/$HOSTNAME/sabnzbd.yaml
  # PVRS
  # MONITORING
  # MAINTENANCE
  - compose/$HOSTNAME/docker-gc.yaml
  # NETWORK
  - compose/$HOSTNAME/gluetun.yaml
  # WEB
  - compose/$HOSTNAME/webapp.yaml
