services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    networks:
      frontend:
        # ipv6_address: fd16:dd1a:c8e4:2::1123
        ipv4_address: 192.168.12.120
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 853:853/udp
      - 7443:443/tcp
      - 3000:3000/tcp
      # - 9080:80/tcp
    volumes:
      - $DOCKERDIR/appdata/adguard/data:/opt/adguardhome/work
      - $DOCKERDIR/appdata/adguard/config:/opt/adguardhome/conf
      - $DOCKERDIR/appdata/cert/live/$DOMAINNAME_NA/fullchain.pem:/opt/adguardhome/certs/fullchain.pem:ro
      - $DOCKERDIR/appdata/cert/live/$DOMAINNAME_NA/privkey.pem:/opt/adguardhome/certs/privkey.pem:ro
    labels:
      - "traefik.enable=true"
      # DNS over HTTPS
      # - "traefik.http.routers.adguard-dns.entrypoints=websecure"
      # - "traefik.http.routers.adguard-dns.rule=Host(`adguard.$DOMAINNAME_NA`) && PathPrefix(`/dns-query`)"
      # - "traefik.http.routers.adguard-dns.service=adguard-dns-svc"
      # - "traefik.http.services.adguard-dns-svc.loadbalancer.server.scheme=https"
      # - "traefik.http.services.adguard-dns-svc.loadBalancer.server.port=443"
      # Adguard Dashboard
      - "traefik.http.routers.adguard-https.entrypoints=websecure"
      - "traefik.http.routers.adguard-https.priority=1"
      - "traefik.http.routers.adguard-https.rule=Host(`adguard.$DOMAINNAME_NA`) || Host(`adguard.$DOMAINNAME_J`)"
      - "traefik.http.routers.adguard-https.middlewares=chain-no-auth@file"
      - "traefik.http.routers.adguard-https.service=adguard-dash-svc"
      - "traefik.http.services.adguard-dash-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.adguard-dash-svc.loadBalancer.server.port=443"
      # - "traefik.http.routers.adguard-https.tls=true"
      # - "traefik.http.routers.adguard-https.tls.certResolver=production"
      # - "traefik.http.routers.adguard-https.tls.domains[0].main=*.$DOMAINNAME_NA"
      # - "traefik.http.routers.adguard-https.tls.domains[0].sans=*.local.$DOMAINNAME_NA"
      # - "traefik.http.routers.adguard-https.tls.domains[1].main=*.$DOMAINNAME_J"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.tcp.routers.adguard-tcp.
      # - "traefik.tcp.routers.adguard-tcp.
      # - "traefik.tcp.routers.adguard-tcp.
      # - "traefik.tcp.routers.adguard-udp.
      # - "traefik.tcp.routers.adguard-udp.
    restart: unless-stopped
