services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    networks:
      - frontend
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 853:853/udp
      # - 3000:3000/tcp
      # - 9080:80/tcp
    volumes:
      - $DOCKERDIR/appdata/adguard/data:/opt/adguardhome/work
      - $DOCKERDIR/appdata/adguard/config:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard-https.rule=Host(`adguard.$DOMAINNAME_NA`) || Host(`adguard.$DOMAINNAME_J`)"
      - "traefik.http.routers.adguard-https.tls=true"
      - "traefik.http.routers.adguard-https.tls.certResolver=production"
      - "traefik.http.routers.adguard-https.entrypoints=websecure"
      - "traefik.http.routers.adguard-https.service=adguard-dash-svc"
      - "traefik.http.services.adguard-dash-svc.loadBalancer.server.port=10232"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.http.routers.adguard-http"
      # - "traefik.tcp.routers.adguard-tcp.
      # - "traefik.tcp.routers.adguard-tcp.
      # - "traefik.tcp.routers.adguard-tcp.
      # - "traefik.tcp.routers.adguard-udp.
      # - "traefik.tcp.routers.adguard-udp.
    restart: unless-stopped
