services:
  certbot:
    container_name: certbot-core
    networks:
      - frontend
    image: certbot/dns-cloudflare

    # Dry Run
    # command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare --agree-tos --email ${ADMIN_EMAIL} -d *.$DOMAINNAME_NA --server https://acme-v02.api.letsencrypt.org/directory --dry-run

    # Issue certificate
    # command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare --agree-tos --email ${ADMIN_EMAIL} -d *.$DOMAINNAME_NA --server https://acme-v02.api.letsencrypt.org/directory

    # Renew certificate
    command: renew --non-interactive --dns-cloudflare --dns-cloudflare-credentials /run/secrets/cloudflare --agree-tos --email ${ADMIN_EMAIL} --server https://acme-v02.api.letsencrypt.org/directory

    volumes:
      - $DOCKERDIR/appdata/cert:/etc/letsencrypt
      - $DOCKERDIR/logs/certbot:/var/log/letsencrypt
    secrets:
      - cloudflare
