services:
  # CrowdSec - Open-source & collaborative security IPS
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - frontend
      - socket_proxy
    ports:
      - "8080:8080"
      - "$CROWDSEC_PROMETHEUS_EXPORT:6060"
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      COLLECTIONS: $CROWDSEC_COLLECTIONS
      GID: "${GID-996}"
      CUSTOM_HOSTNAME: homelab
      LEVEL_WARN: true
      LEVEL_INFO: false
      TZ: $TZ
    volumes:
      - $DOCKERDIR/logs/:/logs/:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log:/var/log:ro
      - $DOCKERDIR/appdata/crowdsec/data:/var/lib/crowdsec/data
      - $DOCKERDIR/appdata/crowdsec/config:/etc/crowdsec
