services:
  # DeUnhealth - Restart your unhealthy containers safely (e.g. containers depending on VPN and VPN reconnects)
  deunhealth:
    image: qmcgaw/deunhealth:latest@sha256:fca3832ace35e3c028d3ec2e6271ac1161ed302b75b34e9dd01db1c106a25802
    container_name: deunhealth
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # profiles: ["apps", "all"]
    environment:
      LOG_LEVEL: info
      HEALTH_SERVER_ADDRESS: 127.0.0.1:9999
      TZ: $TZ
      # DOCKER_HOST: tcp://socket-proxy:2375
