services:
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.3
    container_name: sonarr-exporter
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: "http://sonarr:8989" # or; http://sonarr:8989
      APIKEY: $SONARR_API
    networks:
      - backend
    #    - your_custom_network # optional
    # ports:
    #   - "9707:9707"
    restart: unless-stopped
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.3
    container_name: radarr-exporter
    command: ["radarr"]
    environment:
      PORT: 9708
      URL: "http://radarr:7878" # or; http://radarr:7878
      APIKEY: $RADARR_API
    networks:
      - backend
    #    - your_custom_network # optional
    # ports:
    # - "9708:9708"
    restart: unless-stopped
  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.3
    container_name: prowlarr-exporter
    command: ["prowlarr"]
    environment:
      PORT: 9710
      URL: "http://prowlarr:9696" # or; http://prowlarr:8080
      APIKEY: $PROWLARR_API
      # PROWLARR_BACKFILL: true # optional
      # PROWLARR_BACKFILL_SINCE_DATE: "2023-03-01" # optional
    networks:
      - backend
    # ports:
    # - "9710:9710"
    restart: unless-stopped
  sabnzbd-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.3
    container_name: sabnzbd-exporter
    command: ["sabnzbd"]
    environment:
      PORT: 9711
      URL: "http://sabnzbd:8080" # or; http://sabnzbd:8080
      APIKEY: $SABNZBD_API_KEY
    networks:
      - backend
    # ports:
    #   - "9711:9711"
    restart: unless-stopped
  bazarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.3
    container_name: bazarr-exporter
    command: ["bazarr"]
    environment:
      PORT: 9712
      URL: "http://bazarr:6767" # or; http://bazarr:6767
      APIKEY: $BAZARR_API
    networks:
      - backend
    # ports:
    #   - "9712:9712"
    restart: unless-stopped

  pve-exporter:
    image: prompve/prometheus-pve-exporter
    networks:
      - backend
    container_name: pve-exporter
    environment:
      PVE_USER: $PVE_USER
      PVE_TOKEN_NAME: $PVE_TOKEN_NAME
      PVE_TOKEN_VALUE: $PVE_API
      PVE_VERIFY_SSL: false
    # ports:
    #   - '9221:9221'
    restart: unless-stopped
    # volumes:
    #   - ./pve/pve.yml:/etc/prometheus/pve.yml
