services:
  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["core", "all"]
    networks:
      - frontend
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8081:8080" # Exposing qBittorrent through Docker Host LAN IP
    # #   - 8888:8888/tcp # HTTP proxy
    # #   - 8388:8388/tcp # Shadowsocks
    # #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
      - $DOCKERDIR/appdata/gluetun/forwarded_port:/tmp/gluetun/forwarded_port
    # secrets:
    #   - proton_vpn_pass
    #   - proton_vpn_user
    environment:
      TZ: $TZ
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: openvpn
      # OPENVPN_USER: proton_vpn_user
      # OPENVPN_PASSWORD: proton_vpn_pass
      OPENVPN_USER: $PROTONVPN_USER
      OPENVPN_PASSWORD: $PROTONVPN_PASS
      SERVER_COUNTRIES: Australia
      VPN_PORT_FORWARDING: on
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME_NA`)" # qBittorrent
      # Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-basic-auth@file" # qBittorrent
      # HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc" # qBittorrent
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080" # qBittorrent
