services:
  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    networks:
      - frontend
    restart: always
    # ports:
    #   - "9705:9705"
    volumes:
      - $APPDIR/huntarr:/config
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huntarr.rule=Host(`huntarr.$DOMAINNAME_J`)"
      - "traefik.http.routers.huntarr.entrypoints=websecure"
      - "traefik.http.services.huntarr.loadbalancer.server.port=9705"
      - "traefik.http.middlewares.huntarr-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.huntarr.middlewares=chain-no-auth@file"
      - "traefik.docker.network=frontend"