services:
  jellyseerr:
    image: ghcr.io/seerr-team/seerr:v2.7.3
    container_name: jellyseerr
    dns: "192.168.12.120"
    networks:
      - frontend
    environment:
      - LOG_LEVEL=info
      - TZ=$TZ
      - JELLYFIN_TYPE=emby
    # ports:
    #   - 5055:5055
    volumes:
      - $DOCKERDIR/appdata/jellyseer/config:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseer-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyseer-rtr.rule=Host(`request.local.$DOMAINNAME_NA`) || Host(`request.$DOMAINNAME_NA`)"
      - "traefik.http.routers.jellyseer-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.jellyseer-rtr.service=jellyseer-svc"
      - "traefik.http.services.jellyseer-svc.loadBalancer.server.port=5055"
