services:
  jellyseerr:
    image: fallenbagel/jellyseerr:preview-OIDC
    init: true
    container_name: jellyseerr
    dns: "192.168.12.120"
    networks:
      - frontend
    environment:
      - LOG_LEVEL=info
      - TZ=$TZ
      - JELLYFIN_TYPE=emby
      - PUID=1000
      - PGID=1000
    # ports:
    #   - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    volumes:
      - $DOCKERDIR/appdata/jellyseer/config:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseer-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyseer-rtr.rule=Host(`request.local.$DOMAINNAME_NA`) || Host(`request.$DOMAINNAME_NA`)"
      - "traefik.http.routers.jellyseer-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.jellyseer-rtr.service=jellyseer-svc"
      - "traefik.http.services.jellyseer-svc.loadBalancer.server.port=5055"
