services:
  litkeeper:
    image: ghcr.io/redwoodstory/litkeeper:2.3.1
    restart: unless-stopped
    container_name: litkeeper
    networks:
      - frontend
    volumes:
      - $DATADIR/Audio-ePub/ingest:/litkeeper/app/external
      - $APPDIR/litkeeper/data:/litkeeper/app/data
      - $DOCKERDIR/logs/litkeeper:/litkeeper/app/data/logs
    environment:
      - EXTERNAL_EPUB_PATH=/litkeeper/app/external
      - LITKEEPER_API_TOKEN=$LITKEEPER_API_TOKEN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.litkeeper-https.entrypoints=websecure"
      - "traefik.http.routers.litkeeper-https.rule=Host(`litkeeper.$DOMAINNAME_NA`)"
      - "traeifk.http.routers.litkeeper-https.middlewares=chain-lan-only@file"
      - "traefik.http.routers.litkeeper-https.service=litkeeper-svc"
      - "traefik.http.services.litkeeper-svc.loadBalancer.server.port=5000"
