services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    depends_on:
      socket-proxy:
        condition: service_started
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - frontend
      - socket_proxy
    command: -H tcp://socket-proxy:2375
    ports:
      - 9001:9000
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/appdata/portainer/data:/data
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-rtr.entrypoints=websecure"
      - "traefik.http.routers.portainer-rtr.rule=Host(`port.local.$DOMAINNAME_NA`)"
      - "traefik.http.routers.portainer-rtr.middlewares=chain-lan-only@file"
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9001"
