services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    networks:
      - backend
    # ports:
    #   - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - $DOCKERDIR/appdata/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - $DOCKERDIR/appdata/prometheus/data:/prometheus
    restart: unless-stopped
