services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:3.19.0-1
    container_name: protonmail-bridge
    restart: unless-stopped
    # entrypoint:
    #   ["bash", "/protonmail/entrypoint.sh && sleep 60 && status"]
    networks:
      - frontend
    ports:
      - 1025:25
      - 1143:143
    volumes:
      - $DOCKERDIR/appdata/protonmail:/root
      - $DOCKERDIR/appdata/cert/live/$DOMAINNAME_NA/privkey.pem:/root/.config/protonmail/bridge-v3/key.pem:ro
      - $DOCKERDIR/appdata/cert/live/$DOMAINNAME_NA/fullchain.pem:/root/.config/protonmail/bridge-v3/cert.pem:ro
