services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:20.04.1
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    # ports:
    #   - "8081:8080" # Explosed via gluetun
    volumes:
      - $DOCKERDIR/appdata/gluetun:/tmp/gluetun
      - $DOCKERDIR/appdata/qbittorrent/config:/config
      - $DATADIR/:/media
      - $DOCKERDIR/appdata/qbittorrent/custom-services.d:/custom-services.d
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002
    depends_on:
      gluetun:
        condition: service_healthy
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "ifconfig | grep -q eth0"
      interval: 1m
      timeout: 10s
      retries: 1
    labels: # Traefik labels added via glueten
      - "deunhealth.restart.on.unhealthy=true"
