services:
  qbitrr:
    container_name: qbitrr
    image: feramance/qbitrr:latest
    user: 1000:1000
    tty: true
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/qbitrr/config:/config
      - $DATADIR/downloads:/media/downloads:rw
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: 3
    depends_on:
      - qbittorrent
      - radarr
      - sonarr
      - jellyseerr
