services:
  # Radarr - Movie management
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4.10291-ls296
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    networks:
      frontend:
        ipv4_address: 192.168.12.231
      backend:
        ipv4_address: 192.168.13.231
    # ports:
    # - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr/config:/config
      - $DATADIR:/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.radarr-rtr.rule=Host(`radarr.local.$DOMAINNAME_NA`) || Host(`radarr.$DOMAINNAME_NA`)"
      - "traefik.http.routers.radarr-rtr.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadBalancer.server.port=7878"
