services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network:
      - frontend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/readarr/config:/config
      - $DATADIR:/data #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
    # ports:
    # - 8787:8787
    restart: unless-stopped
