services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "downloads", "all"]
    networks:
      frontend:
        ipv4_address: 192.168.12.230
      backend:
        ipv4_address: 192.168.13.230
    # ports:
    # - "8084:443"
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DATADIR/usenet/:/media/usenet
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
    labels:
      - "traefik.enable=true"
