services:
  # SABnzbd - Binary newsgrabber (NZB downloader)
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.0.3
    container_name: sabnzbd
    healthcheck:
      test: ["CMD", "curl", "-fsS", "-o", "/dev/null", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["apps", "downloads", "all"]
    networks:
      frontend:
        ipv4_address: 192.168.12.230
      backend:
        ipv4_address: 192.168.13.230
    # ports:
    # - "8084:443"
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - $DOCKERDIR/appdata/sabnzbd:/config
      - $DATADIR/usenet/:/media/usenet
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
    labels:
      - "traefik.enable=true"
