services:
  unifi-bouncer:
    image: ghcr.io/teifun2/cs-unifi-bouncer:v1.2.2
    networks:
      - backend
    container_name: bouncer-unifi
    environment:
      CROWDSEC_BOUNCER_API_KEY: $UNIFI_CROWDSEC_API_KEY # docker exec crowdsec cscli bouncers add unifi-bouncer
      CROWDSEC_URL: "http://crowdsec:8080/"
      UNIFI_HOST: "https://unifi.$DOMAINNAME_J"
      UNIFI_USER: $UNIFI_API_USER
      UNIFI_PASS: $UNIFI_API_KEY
      # Only use this if your unifi instance does not have a proper certificate.
      UNIFI_SKIP_TLS_VERIFY: "true"
    restart: unless-stopped
